os: linux
sudo: false
dist: trusty
addons:
  apt:
    packages:
    - lua5.2
git:
  depth: 5
install:
- npm install
script:
- npm start
- npm run pack
deploy:
  provider: releases
  api_key: "$TOKEN"
  file_glob: true
  file: releases/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
env:
  matrix:
    secure: xSm8MWT2xo3+/IDlKb4zIzabULH1d00YYQfNTYeuMkb5Y/MTRHdOeMtK8MOdEd4NyhGmcPnvRf8GRA6ac0bXoCQxGEMqtdUPEqJh7rjX46a4hDM0tN8cAiDOc6zoXDIIFgA7b4MjuqxYXFmjFlaAQdRc0OoSdk4x9fwemPCxUc0zX2id60dNqHlFOuY+cRJC4LPBkdjr7mbMe6sPLhULvFmxvj45CaiB6jfRcsheVMvhNlfFD5uxD2hS3F8n6BR6qouq0qIvbQt+e21uZzt8B8W2NWIpfhq9fejocFjOpHOKtHnv8jWRMoFk6ge/q25AmrYJ8epYdYVBOZW5o56fiBVEy4Yg8149aHVPw5RbuxT1khc0sn0L+ivy6MBkt+S6PICAhhPHGfijGvJHD75FwH53HeyZHqFGg1mjdJcmQk0WTTQcMf3C5eegBZ/Ew6/Ip1bhUr+TwJVqSjiSEPe5OzuAE295SMXmN+M6Bp5+tP/tN4V9dhmxVYQHAKJ5sfYBnUc2Tu4OyEMnFWnVyQo4nASN8KWT0GTwrJHo7ZI/Y/AFqrsRfiEO9tX1GZUtaSfNyUFzHuM16j9QObs1iZjCgqS4kuvO9KA1k3+IVcfY8EmPiA8mlL018l3WSdw+VpOxOcufLNGVIXvN+i2DgbduX7DZurkJosdTRCvRO0SU3vA=
